### PR TITLE
[ISSUE-7] Add rules and messages as dependencies

### LINKED ISSUE #7: Messages are not updated
Hey @marceloadsj,

[This line](https://github.com/marceloadsj/react-indicative-hooks/blob/ab551159a07a408bd3fc753091c1249b3d7c86d0/src/index.js#L42) has a problem. Basically if you pass messages to `useValidateAll` then they are static and are not changing. This is a big problem if you use translations and messages have changed on the fly (without refresh of a page).

Would be nice to have them as a dependency (maybe even rules should be a dependency, I don't know.).

If you are ok the I will open a PR with changes.

p.s. same for `useValidate`.

### PR DESCRIPTION
**Pull request by davityavryan**
Closes #7

### CODE REVIEW

**Comment by marceloadsj** [comment]
I know using a non deterministic way to inject the params on dependency array of react hooks is a bad practice, like:

The way it was:
```javascript
useEffect(() => {

}, Object.values);
```

Or the new way:
```javascript
useEffect(() => {

}, [...Object.values]);
```

But, to avoid breaking changes, I think this will be the best approach for now.
I'm merging this one into master, and we can plan a new small release.

**Comment by davityavryan** [comment]
Hey @marceloadsj ,
Can I have a release for this one please?
I should fix the bug in our system today ;(

**Comment by marceloadsj** [comment]
Hey man, yes yes! Sorry my delay. Let me do this here quickly! :)

**Comment by marceloadsj** [comment]
Done mate, again sorry my delay!

**Pull request merged**
